apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-conf
  namespace: mimosa-demo
data:
  nginx.conf: |
    server {
      listen 80;
      server_name _;

      # Simple IPS-like reflex drop for SQLi attempts.
      if ($request_uri ~* "union.*select") {
        return 403;
      }

      # Allowlist path so EDR demo can trigger.
      location /spawn {
        proxy_pass http://webapp:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
      }

      location / {
        proxy_pass http://webapp:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
    }
