services:
  bus:
    image: nats:2.10
    ports:
      - "4222:4222"   # client
      - "8222:8222"   # monitoring

  node:
    build: ./node
    depends_on: [bus]
    environment:
      NATS_URL: nats://bus:4222
      # NODE_ID is optional; will default to container hostname
      WINDOW_MS: "5000"
      THRESH: "20"
      BLOCK_TTL_SEC: "180"
      BAD_PATHS: "/wp-login.php,/xmlrpc.php,/admin/login"
      BAD_STATUS: "401,403"

  controller:
    build: ./controller
    depends_on: [bus]
    environment:
      NATS_URL: nats://bus:4222
      QUORUM: "1"
      DEFAULT_TTL_SEC: "180"
      HTTP_PORT: "3000"
    ports:
      - "3000:3000"  # Interface web + WebSocket

  traffic:
    build: ./traffic
    depends_on: [bus]
    environment:
      NATS_URL: nats://bus:4222

  natsbox:
    image: synadia/nats-box
    depends_on: [bus]
    entrypoint: ["/bin/sh","-lc","sleep infinity"]
