services:
  bus:
    image: nats:2.10
    ports: ["4222:4222","8222:8222"]  # client / monitoring

  node:
    build: ./node
    environment:
      NODE_ID: node-1
      NATS_URL: nats://bus:4222
    depends_on: [bus]

  controller:
    build: ./controller
    environment:
      NATS_URL: nats://bus:4222
      QUORUM: "1"           # "2" => au moins 2 nodes d’accord
      DEFAULT_TTL_SEC: "180"
      WS_PORT: "8080"
    depends_on: [bus]
    ports: ["8080:8080"]

  dashboard:
    build: ./dashboard
    environment:
      NEXT_PUBLIC_WS_URL: ws://localhost:8080
    depends_on: [controller]
    ports: ["3000:3000"]

  traffic:
    build: ./traffic
    environment:
      NATS_URL: nats://bus:4222
    depends_on: [bus]

  natsbox:
    image: synadia/nats-box
    depends_on: [bus]
    entrypoint: ["/bin/sh","-lc","sleep infinity"]
